# -*- coding: utf-8 -*-
"""Tugas3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XbszASi313rmprQmE7gJwLQwY8X3oLj6
"""

# Program untuk mencari nilai tertinggi dari 5 siswa

# Inisialisasi list untuk menyimpan nilai
nilai_siswa = []

# Input nilai 5 siswa menggunakan perulangan
for i in range(5):
    nilai = float(input(f"Masukkan nilai siswa ke-{i+1}: "))
    nilai_siswa.append(nilai)

# Mencari nilai tertinggi dan indeksnya
nilai_tertinggi = max(nilai_siswa)
siswa_tertinggi = nilai_siswa.index(nilai_tertinggi) + 1  # +1 agar urutan siswa dimulai dari 1

# Menampilkan hasil
print("\nNilai tertinggi adalah:", nilai_tertinggi)
print("Diperoleh oleh siswa ke-", siswa_tertinggi)