# -*- coding: utf-8 -*-
"""Tugas2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHTdYxhFajqqG5OfFr5TyY_aLmCyydRW
"""

# Program untuk menghitung rata-rata dan menentukan kelulusan

# Input nilai dari 3 mata pelajaran
nilai1 = float(input("Masukkan nilai mata pelajaran 1: "))
nilai2 = float(input("Masukkan nilai mata pelajaran 2: "))
nilai3 = float(input("Masukkan nilai mata pelajaran 3: "))

# Hitung rata-rata
rata_rata = (nilai1 + nilai2 + nilai3) / 3

# Menentukan status kelulusan
if rata_rata >= 75:
    status = "Lulus"
else:
    status = "Tidak Lulus"

# Tampilkan hasil
print("Rata-rata nilai:", rata_rata)
print("Status kelulusan:", status)