# -*- coding: utf-8 -*-
"""Tugas1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzU5zwHP-LI4Bmjg8xL8aqZIQxUkN1Ry
"""

# Program untuk menghitung total harga 3 barang

# Input harga barang
barang1 = float(input("Masukkan harga barang ke-1: "))
barang2 = float(input("Masukkan harga barang ke-2: "))
barang3 = float(input("Masukkan harga barang ke-3: "))

# Hitung total harga
total = barang1 + barang2 + barang3

# Tampilkan total
print("Total harga yang harus dibayar adalah: Rp", total)