# -*- coding: utf-8 -*-
"""Tugas5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mK-SrRIZeVjScrDaJKQNd8P7S5bP69W
"""

# Program untuk menghitung total bayar setelah diskon jika belanja > Rp500.000

# Input total belanja dari pengguna
total_belanja = float(input("Masukkan total belanja (Rp): "))

# Cek apakah mendapatkan diskon
if total_belanja > 500000:
    diskon = total_belanja * 0.10
    total_bayar = total_belanja - diskon
    print(f"Anda mendapat diskon 10% sebesar Rp{diskon}")
else:
    total_bayar = total_belanja
    print("Anda tidak mendapat diskon.")

# Tampilkan total yang harus dibayar
print(f"Total yang harus dibayar: Rp{total_bayar}")